aws-pkg_secrets:
  seed:
    profile_name: ""
    iam_user_name: ""
    user_policy_json: ""
sops:
  lastmodified: "2026-04-17T23:35:03Z"
  mac: ENC[AES256_GCM,data:JFiKmd2yuC37yOkzEUZ7Gq3SSzEDw7Z0R2NkeTcu3pL68Hq3tYTYR3Om+D1VMDlSM+TuDrgHTxdUqp0htzmQIn9plhmELotZWXewYmvvp8124Tjy3RUijN5ahBNTUaNVqop/DzuMxpdTL4BBCpLKxPOVLdz92HcWTgYKFKztX8c=,iv:tYIDwsGBdd9atxYeRl5Vr4XyHruy9w1tjS8Jd7aoTwU=,tag:ycTt1wdBgOFx8fTb7Wi+jg==,type:str]
  pgp:
    - created_at: "2026-04-13T02:48:56Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQGMAweuHx4I2A4UAQv9G/wRMZXoygHIDB8EhpbG0lQWxvSBtP0Unwn0VII2hnXC
        IBpJPrODaSl8mH9cgvZf697T2HzS0WR4BGIhjkIlKVdNv0nRJc+LyVKY4GpdddgP
        rd09YQdlYoRFkwFlJ0dYdFwSrOdAkXcjxujGze5pfO+FwyN+IL5/elTOPAB385xj
        yyYTOxXvuW0uZiWem5rs1LZ+ldpz2COC3anO02EC6xgVNS5a9jHCYNDgB+TIyKA6
        JpLrKCrEj9/7InhNGwJlirl6soaHfH7bgzE58uSQ0SDYZFFgosrWp70wjoV/la6p
        6zPJRyP93q/ytFbvQkfpexrzGBmJnb5eVUH8TaaRmOoLGilt6yAAiCmaNT3M2MyY
        wLHJm7vrZ4iRdd0IamqUDmiwbEcU/U/XgjKbNrKZJPfn3D13jbtfFh+SociFuqzg
        Cl4GNxUG5XPrPvl+UahX6pxUOb8mfH+AYtF/7EAvR3uGQ+vDfoxXGD+2ic94/rFr
        AkFas1LJft5QK0xeJF+u0lwBSTDX1rNkohlPeNcdWoWpJAP/fdos/54zPhUH1Y01
        ZiWfoGIN4j2u4dbM/a02bkiF0LxKI8xdtqEd48Dm3DSJNU7xYol7vxRT6Gp7WTc/
        vdnUK+8RviwiS8b7NA==
        =RkKJ
        -----END PGP MESSAGE-----
      fp: 446B4127CF4E00C389579F20986E9FAE2FB2BEBD
    - created_at: "2026-04-13T02:48:56Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA1MQLyG6dlTlAQ/+JaD3984W4YGZCR+Ip5fI7VyI9fzGZT2GCk4jOTAlRzEb
        uj8ZEUhEUGb09aE85qWOJoeXlH/8RD3c4xmcXlcb22OYdHiwDhAH/U8ToX4Kz8Of
        iDPoaMNt7JRpyiA3ebiqRhuIMUEZ36nfj4cf/Gp5Jev6ogp/lk5YtCeRTWS5mq74
        sBzZBM0xwd/nx/SYBXyxelc8Cx1T/NPCcoKXIRtgE7TPC2/Eae3YHK3nJ6v83d8Q
        L62wIi98hAw2oV2IY+4ocR7OFu0RS3dp/RtdksJP+eqRTD9PjAkWs5eK7GQrmrJC
        WrtpmmUfhCQhFBZyH3Rs/cQz+gBZ0KhSteykosLYmv7oZm+fUd78ulaI7Z6sqwZc
        eX06DMsGE5l4bvBb+ICnwNPp7KmiHsC3ORYhMmZO/+LXy7wP9QarH52cDvi+XC9Z
        6D3iOpAbPre0LqF57HSJho4RvPvArfBWKXzaAjOG/YhrbbhbDZLHUPWfxaFsTdJL
        r6PYgBmdbAgWjJ/3DUNM6nONHADZuS7LgtdgdC7EnKSQ33JyoBqwqJ/5PFxFX9LM
        sBF56WTrL2J2cnNGdFVh4phx1qF9krhHSfs/T4gm1cPykSaH3/ubAfWTzYOGWc+U
        +hy31VzXBtW1A+UAy4V9cdEabQ6/TN4QtqdywEOTt8ZVK1kcruJ6Quuf9KC0w/vS
        XAFhM6ZQ6nvjbDaJI179piIbwL2C5YWB1jyHa2oly4w+hVcmrSZ+tmjxJNL67C4z
        +XFYsyP5retzgOmGxrwvsmYA58U/u8BMhEa0OB/ddfJK1nVcbEbM3lPlUp+M
        =cAUN
        -----END PGP MESSAGE-----
      fp: 1FAFFDF2C76C758F736178E2B776DF4CEB6B692B
  unencrypted_suffix: _unencrypted
  version: 3.10.2
